services:
  
  jupyterhub:
    image: jupyterhub/jupyterhub:latest
    build:
      context: ./
      dockerfile: ./Dockerfile.hub
    container_name: jupyterhub
    ports:
      - "8000:8000"
    networks:
      - jupyterhub-network
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./create_users.sh:/srv/jupyterhub/create_users.sh
      - jupyterhub-data:/srv/jupyterhub/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "/srv/jupyterhub/create_users.sh && jupyterhub -f /srv/jupyterhub/jupyterhub_config.py"
    environment:
      - JUPYTERHUB_CRYPT_KEY=${JUPYTERHUB_CRYPT_KEY:-$(openssl rand -hex 32)}
      - JUPYTERHUB_USER_IMAGE=userimage:1
    restart: unless-stopped

volumes:
  jupyterhub-data:

networks:
  jupyterhub-network:
    name: jupyterhub-network
